#!/usr/bin/env bash
# build-single.sh — combine modular scripts into dist/rustdesk-install.sh
#
# The combined installer is a standalone script — no repo checkout needed.
# Copy it to any Debian 13 server and run it with a .env file present.
#
# Usage:
#   bash build-single.sh
#   # Output: dist/rustdesk-install.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${REPO_DIR}/dist/rustdesk-install.sh"
SCRIPTS_DIR="${REPO_DIR}/scripts"

mkdir -p "${REPO_DIR}/dist"

echo ""
echo "[INFO]  Building combined installer..."
echo "[INFO]  Source: ${SCRIPTS_DIR}"
echo "[INFO]  Output: ${OUTPUT}"
echo ""

# ── include_script ─────────────────────────────────────────────────────────────
# Strips from a script file:
#   - shebang lines (#!/...)
#   - bare `set -euo pipefail` lines (we add one at the top)
#   - blocks between STANDALONE_ONLY_BEGIN and STANDALONE_ONLY_END markers
# Optionally prepends a section comment banner.
include_script() {
    local file="$1"
    local section_comment="${2:-}"

    if [[ -n "$section_comment" ]]; then
        echo ""
        echo "# ╔══════════════════════════════════════════════════════════════════╗"
        printf "# ║  %-64s║\n" "$section_comment"
        echo "# ╚══════════════════════════════════════════════════════════════════╝"
    fi

    awk '
        /# STANDALONE_ONLY_BEGIN/ { skip=1; next }
        /# STANDALONE_ONLY_END/   { skip=0; next }
        skip                      { next }
        /^#!/                     { next }
        /^set -euo pipefail$/     { next }
        { print }
    ' "$file"
}

# ── Build combined file ────────────────────────────────────────────────────────
{
    # Header
    echo "#!/usr/bin/env bash"
    echo "# dist/rustdesk-install.sh — RustDesk Server OSS combined installer"
    echo "# Generated by build-single.sh on $(date)"
    echo "# Repo: https://github.com/<your-username>/rustdesk-server-debian"
    echo "#"
    echo "# This is a standalone script — no repo clone required."
    echo "#"
    echo "# Usage:"
    echo "#   1. Create .env in the same directory (or /tmp/rustdesk-install.env):"
    echo "#        SERVER_IP=<your-public-ip>"
    echo "#        ADMIN_USER=rdadmin"
    echo "#        SSH_PORT=2222"
    echo "#   2. Run: sudo bash rustdesk-install.sh"
    echo ""
    echo "set -euo pipefail"

    # Shared library (defines helpers, status tracking, colour codes)
    include_script "${SCRIPTS_DIR}/lib-common.sh" "Shared library"

    # Steps (each defines a function; main() calls them in order)
    include_script "${SCRIPTS_DIR}/00-preflight.sh"          "Step 00 — Pre-flight checks"
    include_script "${SCRIPTS_DIR}/01-packages.sh"           "Step 01 — Base packages"
    include_script "${SCRIPTS_DIR}/02-docker.sh"             "Step 02 — Docker Engine"
    include_script "${SCRIPTS_DIR}/03-user-hardening.sh"     "Step 03 — Admin user"
    include_script "${SCRIPTS_DIR}/04-ssh-hardening.sh"      "Step 04 — SSH hardening"
    include_script "${SCRIPTS_DIR}/05-firewall.sh"           "Step 05 — UFW firewall"
    include_script "${SCRIPTS_DIR}/06-rustdesk-compose.sh"   "Step 06 — Compose setup"
    include_script "${SCRIPTS_DIR}/07-start-services.sh"     "Step 07 — Start services"
    include_script "${SCRIPTS_DIR}/08-show-keys.sh"          "Step 08 — Show keys"
    include_script "${SCRIPTS_DIR}/09-final-status.sh"       "Step 09 — Final summary"

    # Main entry point
    cat << 'MAIN_EOF'

# ╔══════════════════════════════════════════════════════════════════╗
# ║  Main entry point                                                ║
# ╚══════════════════════════════════════════════════════════════════╝

main() {
    # Load .env from current directory or /tmp/rustdesk-install.env
    if [[ -f "./.env" ]]; then
        # shellcheck source=/dev/null
        source "./.env"
    elif [[ -f "/tmp/rustdesk-install.env" ]]; then
        # shellcheck source=/dev/null
        source "/tmp/rustdesk-install.env"
    fi

    export ADMIN_USER="${ADMIN_USER:-rdadmin}"
    export SSH_PORT="${SSH_PORT:-2222}"
    export SERVER_IP="${SERVER_IP:-}"
    export RUSTDESK_DATA_DIR="${RUSTDESK_DATA_DIR:-/opt/rustdesk/data}"
    export DOCKER_LOG_MAX_SIZE="${DOCKER_LOG_MAX_SIZE:-10m}"
    export DOCKER_LOG_MAX_FILE="${DOCKER_LOG_MAX_FILE:-3}"
    export UNATTENDED_UPGRADES_EMAIL="${UNATTENDED_UPGRADES_EMAIL:-}"

    require_root

    echo ""
    echo "+----------------------------------------------------------------------+"
    echo "|  RustDesk Server OSS — Combined Installer (Debian 13 amd64)         |"
    echo "+----------------------------------------------------------------------+"
    printf "|  Server IP  : %-54s |\n" "${SERVER_IP:-<not set>}"
    printf "|  Admin user : %-54s |\n" "$ADMIN_USER"
    printf "|  SSH port   : %-54s |\n" "$SSH_PORT"
    printf "|  Data dir   : %-54s |\n" "$RUSTDESK_DATA_DIR"
    echo "+----------------------------------------------------------------------+"
    echo ""

    step_00_preflight
    step_01_packages
    step_02_docker
    step_03_user_hardening
    step_04_ssh_hardening
    step_05_firewall
    step_06_rustdesk_compose
    step_07_start_services
    step_08_show_keys
    step_09_final_status
}

main "$@"
MAIN_EOF

} > "$OUTPUT"

chmod +x "$OUTPUT"

LINE_COUNT="$(wc -l < "$OUTPUT")"
echo "[OK]   Combined installer written: $OUTPUT"
echo "[INFO] Lines: ${LINE_COUNT}"
echo ""
echo "To deploy on a remote server:"
echo "  scp $OUTPUT root@<server>:/tmp/"
echo "  scp .env root@<server>:/tmp/rustdesk-install.env"
echo "  ssh root@<server> 'bash /tmp/rustdesk-install.sh'"
echo ""
