#!/usr/bin/env bash
# 06-rustdesk-compose.sh — deploy compose.yml and .env to /opt/rustdesk
#
# Creates the deploy directory, data directory, writes compose.yml with
# runtime values substituted, and writes a runtime .env.
# Both hbbs and hbbr mount the same data volume — hbbr reads hbbs's ed25519 key.
#
# Standalone: sudo bash scripts/06-rustdesk-compose.sh
# Sourced by: install.sh

set -euo pipefail

step_06_rustdesk_compose() {
    step "RustDesk Compose setup"

    SERVER_IP="${SERVER_IP:-}"
    RUSTDESK_DATA_DIR="${RUSTDESK_DATA_DIR:-/opt/rustdesk/data}"
    DOCKER_LOG_MAX_SIZE="${DOCKER_LOG_MAX_SIZE:-10m}"
    DOCKER_LOG_MAX_FILE="${DOCKER_LOG_MAX_FILE:-3}"
    DEPLOY_DIR="/opt/rustdesk"

    [[ -n "$SERVER_IP" ]] || die "SERVER_IP must be set. Check .env."

    # ── Deploy directory ──────────────────────────────────────────────────────
    mkdir -p "$DEPLOY_DIR"
    ok "Deploy directory: $DEPLOY_DIR"
    add_status "RustDesk" "Deploy dir" PASS "$DEPLOY_DIR"

    # ── Data directory ────────────────────────────────────────────────────────
    # RustDesk containers run as root and write keys to /root (→ ./data).
    # 750 prevents other local users from reading the private key.
    mkdir -p "$RUSTDESK_DATA_DIR"
    chown root:root "$RUSTDESK_DATA_DIR"
    chmod 750 "$RUSTDESK_DATA_DIR"
    ok "Data directory: $RUSTDESK_DATA_DIR (750)"
    add_status "RustDesk" "Data dir" PASS "$RUSTDESK_DATA_DIR"

    # ── Write compose.yml ─────────────────────────────────────────────────────
    # host networking: required so UDP hole-punching preserves source ports.
    # -r ${SERVER_IP}: tells clients which relay address hbbr is reachable at.
    #   Must be the public IP/FQDN, not 127.0.0.1 or a private address.
    # Shared volume: both services mount the same path so hbbr reads hbbs's key.
    cat > "${DEPLOY_DIR}/compose.yml" << EOF
# /opt/rustdesk/compose.yml
# Generated by 06-rustdesk-compose.sh on $(date)

services:

  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs -r ${SERVER_IP}
    network_mode: host
    volumes:
      - ${RUSTDESK_DATA_DIR}:/root
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${DOCKER_LOG_MAX_SIZE}"
        max-file: "${DOCKER_LOG_MAX_FILE}"

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    network_mode: host
    volumes:
      - ${RUSTDESK_DATA_DIR}:/root
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "${DOCKER_LOG_MAX_SIZE}"
        max-file: "${DOCKER_LOG_MAX_FILE}"
EOF

    ok "compose.yml written: ${DEPLOY_DIR}/compose.yml"
    add_status "RustDesk" "compose.yml" PASS "${DEPLOY_DIR}/compose.yml"

    # ── Write runtime .env ────────────────────────────────────────────────────
    # 600 permissions: only root can read this file
    cat > "${DEPLOY_DIR}/.env" << EOF
# /opt/rustdesk/.env — runtime environment
# Generated by 06-rustdesk-compose.sh on $(date)
SERVER_IP=${SERVER_IP}
RUSTDESK_DATA_DIR=${RUSTDESK_DATA_DIR}
DOCKER_LOG_MAX_SIZE=${DOCKER_LOG_MAX_SIZE}
DOCKER_LOG_MAX_FILE=${DOCKER_LOG_MAX_FILE}
EOF

    chmod 600 "${DEPLOY_DIR}/.env"
    ok "Runtime .env written: ${DEPLOY_DIR}/.env (600)"
    add_status "RustDesk" "Runtime .env" PASS "${DEPLOY_DIR}/.env"
}

# ── Standalone execution ───────────────────────────────────────────────────────
# STANDALONE_ONLY_BEGIN
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "${SCRIPT_DIR}/lib-common.sh"
    load_env "$SCRIPT_DIR"
    require_root
    step_06_rustdesk_compose
fi
# STANDALONE_ONLY_END
